apiVersion: multicluster.agones.dev/v1
kind: GameServerAllocationPolicy
metadata:
  name: wordfleet-local-policy
  namespace: wordfleet
spec:
  priority: 1
  weight: 100
  connectionInfo:
    allocationEndpoints:
      - 34.0.0.1
    clusterName: wordfleet-local
    namespace: wordfleet
    secretName: allocator-client.default
