apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordfleet-api
  namespace: wordfleet
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  rules:
    - http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: control-plane
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: control-plane
                port:
                  number: 80
