apiVersion: v1
kind: Service
metadata:
  name: wordfleet-session
  namespace: wordfleet
spec:
  selector:
    agones.dev/fleet: wordfleet-session
  ports:
    - name: ws
      port: 8090
      targetPort: 8090
